### ISSUE TITLE
Compability with Bluetooth module

### ISSUE THREAD

**Issue by jusierra** [theairboard/TheAirBoard#3]
Hi,

I just received my airboard, thanks a lot. 
I just asking myself how can I upload sketch on it if I don't have the wifi or xbee module you sent with some package ? I have a hc 06 bluetooth module, can I use it as well ?
If yes, how ? 
Thanks a lot.

**Comment by theairboard** [comment]
To upload wirelessly, you need remote RTS/DTR flow control which doesn't seem to be implemented on hc 06.
RN41, RN42, BLE-LINK, Bluefruit EZ-Link, XBee and WiFly for instance can provide remote flow control.
